name: syntax-check

on:
  pull_request:
  push:
    branches:
    - develop
    - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Cleanup previous run
      run: docker run --rm -v ${{ github.workspace }}:/workspace alpine sh -c "rm -rf /workspace/test/aperturedb/db* /workspace/test/aperturedb/logs" || true
      continue-on-error: true

    - uses: actions/checkout@v3

    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - uses: pre-commit/action@v3.0.1

    - uses: luisremis/find-trailing-whitespace@master
