name: main

on:
  push:
    branches:
      - main

jobs:
  build-test:

    runs-on:
    - self-hosted
    - deployer

    steps:

    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Login to Google Cloud
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        project_id:          ${{ secrets.GCP_SERVICE_ACCOUNT_PROJECT_ID }}
        export_default_credentials: true

    - name: Build and Run Tests
      env:
        AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_DEFAULT_REGION:    ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      run: 'EXCLUDE_DOCUMENTATION=1 EXCLUDE_DEPLOY=1 ./ci.sh'
      shell: bash

  build_and_deploy_docs:
    needs:
    - build-test

    runs-on:
    - self-hosted
    - deployer

    steps:

    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build Notebook,docs Docker
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        EXCLUDE_TESTING=1 EXCLUDE_DEPLOY=1 ./ci.sh
      shell: bash

    - name: Publish to PyPi
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        pip3 install twine
        bash publish.sh

    - name: Tag release version
      run: './tag.sh'
      shell: bash

    - name: GitHub Release
      run: 'TOKEN=${{ secrets.GITHUBPAT }} ./github-release.sh'
      shell: bash

  deploy_web_services:
    needs:
    - build-test
    - build_and_deploy_docs

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Apply Terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        EXCLUDE_TESTING=1 EXCLUDE_DOCUMENTATION=1 ./ci.sh
      shell: bash

  trigger_demos_buils:
    runs-on: ubuntu-latest
    needs:
      - build_and_deploy_docs
    steps:
    - uses: actions/checkout@v3
    - name: repository dispatch
      run: |
        curl -X POST https://api.github.com/repos/aperture-data/demos/actions/workflows/11368906/dispatches \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.GITHUBPAT }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        -d '{"ref":"master","inputs":{}}'

      shell: bash