# This is a basic workflow to run tests on commit/PRs on develop

name: main

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events
  # but only for the develop, master, and release branches
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs
# that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-test"
  build-test:
    # The type of runner that the job will run on Ubuntu 18.04 (latest)
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be
    # executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE,
      # so your job can access it
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Run Tests
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION:    ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          pip3 install ipython torch torchvision boto3
          cd test
          bash run_test.sh
          ONLY_DEFINES=1 bash coverage.sh

  build_and_deploy_docs:

    # The type of runner that the job will run on Ubuntu 18.04 (latest)
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be
    # executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE,
      # so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build Notebook,docs Docker
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: './ci.sh'
        shell: bash

      - name: Publish to PyPi
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          pip3 install twine
          bash publish.sh

      - name: Tag release version
        run: './tag.sh'
        shell: bash
      
      - name: GitHub Release
        run: 'TOKEN=${{ secrets.GITHUBPAT }} ./github-release.sh'
        shell: bash

  deploy_artifacts_staging_environment:
    needs:
      - build-test
      - build_and_deploy_docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set release version
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: './configure_deployment.sh'
        shell: bash
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG_MICROK8S }}
        with:
          args: apply -f deploy/
