# This is a basic workflow to run tests on commit/PRs on develop

name: CI-develop

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events
  # but only for the develop, master, and release branches
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs
# that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-test"
  build-test:
    # The type of runner that the job will run on Ubuntu 18.04 (latest)
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be
    # executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE,
      # so your job can access it
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Run Tests
        run: |
          pip3 install .
          cd test
          bash run_test.sh

      - name: Build Notebook Docker
        run: |
          cd docker
          bash
